In [9]:
import pandas as pd
import numpy as np
import mysql.connector
import psycopg2
from datetime import datetime


In [10]:
# conn = psycopg2.connect(
#     host="191.191.2.63",
#     database="Totle-2nd-Mask",
#     user="admin",
#     password="Ab123456")
# print("Connect to PG Admin 4")
# myconn = conn.cursor()
# myconn.execute("select * from twomask_cpk")
# reconn = myconn.fetchall()


In [11]:
mydb = mysql.connector.connect(
  host="163.50.57.98",
  user="sandbox_user",
  password="Admin!@#"
  )
print("connect MySQL")

mycox = mydb.cursor()
mycox.execute("select * from mt900.twomask_cpk;")
records = mycox.fetchall()

connect MySQL


In [12]:
df = pd.DataFrame(records)

df.drop([0], axis=1, inplace=True)

df.to_csv("a.csv",index=False)

rd = pd.read_csv("a.csv",index_col=False)
rd.reset_index(drop=True)
x = input('>>>>')
rd = rd.loc[rd['6'] == x]
# # rd = rd.reset_index()
print(rd)

        1      2      3      4                    5         6   7
0   4.566  0.581  4.609  0.565  2023-06-23 19:21:06  236BF233 NaN
1   4.549  0.582  4.585  0.557  2023-06-23 19:21:06  236BF233 NaN
2   4.552  0.577  4.630  0.577  2023-06-23 19:21:06  236BF233 NaN
3   4.592  0.574  4.623  0.585  2023-06-23 19:21:07  236BF233 NaN
4   4.576  0.576  4.658  0.599  2023-06-23 19:21:07  236BF233 NaN
5   4.590  0.575  4.638  0.594  2023-06-23 19:21:07  236BF233 NaN
6   4.573  0.570  4.622  0.583  2023-06-23 19:21:07  236BF233 NaN
7   4.584  0.560  4.611  0.591  2023-06-23 19:21:07  236BF233 NaN
8   4.579  0.570  4.638  0.596  2023-06-23 19:21:07  236BF233 NaN
9   4.600  0.561  4.618  0.576  2023-06-23 19:21:07  236BF233 NaN
10  4.598  0.582  4.611  0.615  2023-06-23 19:21:07  236BF233 NaN


In [17]:
LSL = 4.4
USL = 4.8
number = [LSL,USL]
target = sum(number)/len(number)
print("Ave >>",target)
CPK_lost = x

# def Cp(mylist, usl, lsl):
#             arr = np.array(mylist)
#             arr = arr[~np.isnan(arr)]
#             arr = arr.ravel()
#             sigma = np.std(arr)
#             Cp = float(usl - lsl) / (6 * sigma)
#             # print("<>>>>>>>>>>>>",Cp)
#             return Cp

def Cpk(mylist, usl, lsl):
            arr = np.array(mylist)
            arr = arr[~np.isnan(arr)]
            arr = arr.ravel()
            sigma = np.std(arr)
            m = np.mean(arr)
            Cpu = float(usl - m) / (3 * sigma)
            Cpl = float(m - lsl) / (3 * sigma)
            Cpk = np.min([Cpu, Cpl])
            print(np.array(mylist))
            return Cpk

# Cp_front_pos = Cp(rd["1"],USL,LSL)
# Cp_front_width = Cp(rd["2"],USL,LSL)
# Cp_back_pos = Cp(rd["3"],USL,LSL)
# Cp_back_width = Cp(rd["4"],USL,LSL)

Cpk_front_pos = Cpk(rd["1"],USL,LSL)
Cpk_front_width = Cpk(rd["2"],USL,LSL)
Cpk_back_pos = Cpk(rd["3"],USL,LSL)
Cpk_back_width = Cpk(rd["4"],USL,LSL)

datacpk_front_pos = '%.4f'%(Cpk_front_pos)
datacpk_front_width = '%.4f'%(Cpk_front_width)
datacpk_back_pos = '%.4f'%(Cpk_back_pos)
datacpk_back_width = '%.4f'%(Cpk_back_width)

print('Cpk-front_pos   >>>',datacpk_front_pos)
print('Cpk-front_width >>>',datacpk_front_width)
print('Cpk-back_pos    >>>',datacpk_back_pos)
print('Cpk-back_width  >>>',datacpk_back_width)
print('lost production',CPK_lost)

Ave >> 4.6
[4.566 4.549 4.552 4.592 4.576 4.59  4.573 4.584 4.579 4.6   4.598]
[0.581 0.582 0.577 0.574 0.576 0.575 0.57  0.56  0.57  0.561 0.582]
[4.609 4.585 4.63  4.623 4.658 4.638 4.622 4.611 4.638 4.618 4.611]
[0.565 0.557 0.577 0.585 0.599 0.594 0.583 0.591 0.596 0.576 0.615]
Cpk-front_pos   >>> 3.6244
Cpk-front_width >>> -174.9465
Cpk-back_pos    >>> 3.2472
Cpk-back_width  >>> -81.6759
lost production 236BF233


In [14]:
dt = datetime.now()

ts =datetime.timestamp(dt)

date_time = datetime.fromtimestamp(ts)

times = date_time.strftime("%d-%m-%Y  %H:%M:%S")
print("date and time is :",dt)
print("Result 1:", times)

date and time is : 2023-07-31 12:31:04.787018
Result 1: 31-07-2023  12:31:04


In [15]:
connection = psycopg2.connect(user="admin",
                                  password="Ab123456",
                                  host="191.191.2.179",
                                  port="5432",
                                  database="Totle-2nd-Mask")
# connection

cursor = connection.cursor()


a = "INSERT INTO cpk_data(cpk_lost ,cpk_front_pos, cpk_front_width, cpk_back_pos, cpk_back_width,d,times) VALUES (%s, %s, %s, %s, %s, %s, %s)"
b = (CPK_lost, datacpk_front_pos, datacpk_front_width, datacpk_back_pos, datacpk_back_width,dt,times)
cursor.execute(a,b)
connection.commit()
print("INSERT INTO SUBMIT MY DATABASE PG ADMIN")


INSERT INTO SUBMIT MY DATABASE PG ADMIN


In [16]:
# mycursor = mydb.cursor()

# sql = "INSERT INTO mt900.CPK_lost (cpk_lost ,cpk_front_pos, cpk_front_width, cpk_back_pos, cpk_back_width) VALUES (%s, %s, %s, %s, %s)"
# val = (CPK_lost, datacpk_front_pos, datacpk_front_width, datacpk_back_pos, datacpk_back_width)
# mycursor.execute(sql, val)

# mydb.commit()
# print("seucsss")